Flowpack:
  DecoupledContentStore:
    extensions:
      # Register additional content release writers, being called for every finished node which should be added
      # to the content release.
      #  (must implement ContentReleaseWriterInterface)
      contentReleaseWriters:
        gzipCompressed:
          className: Flowpack\DecoupledContentStore\NodeRendering\Extensibility\ContentReleaseWriters\GzipWriter

    redisKeyPostfixesForEachRelease:
      renderedDocuments:
        redisKeyPostfix: 'renderedDocuments'
        transfer: true
        transferMode: 'hash_incremental'
        isRequired: true
      renderedMetadata:
        redisKeyPostfix: 'renderedMetadata'
        transfer: true
        transferMode: 'hash_incremental'
        isRequired: true
