Flowpack:
  DecoupledContentStore:
    redisContentStores:
      # the "Primary" content store is the one Neos writes to during building the content release.
      primary:
        label: 'Primary'
        hostname: 127.0.0.1
        port: 6379
        database: 11

        # How many content releases to keep before cleaning them up.
        #
        # NOTE: the log-retention count is not configured here, but in prunner (see `pipelines.yml`, underneath
        # pipelines.do_content_release.retention_count and pipelines.manually_transfer_content_release.retention_count).
        contentReleaseRetentionCount: 20

      # you can add additional, arbitrarily named, content stores here - they appear in the UI.
      # If you do this, see the hints in the README "Copy Content Releases to a different Redis instance".

    nodeRendering:
      # Allows to filter the list of node types which should end up in the content store; and in the content
      # enumeration. Supports the format of NodeInterface::getChildren() (or NodeTypeConstraintFactory, which is
      # its internal implementation)
      # Example:
      # Neos.Neos:Document,!My.Package:Bar
      nodeTypeWhitelist: 'Neos.Neos:Document'

      # Allows to filter the list of enumerated URLs which should end up in the content store.
      #
      # This is sometimes needed because the same node is accessed via different URLs, and some URLs are internal and should
      # not end up in the content store.
      #
      # We match the full URL (including hostname and prefix; so like "http://foo.bar/bla") with this regex.
      #
      # If "FALSE", the blacklisting is disabled.
      urlExcludelistRegex: false

      # Set to `true` to render relative resource URIs
      useRelativeResourceUris: false

      # Add full HTTP message to the output of the content store
      addHttpMessage: false



    extensions:
      # Extend Node Rendering by generating additional data for each rendering, interleaved with the content cache.
      #
      #  (must implement DocumentMetadataGeneratorInterface)
      # -
      #   className: Fully\Qualified\Classname
      documentMetadataGenerators: []

      # Register additional content release writers, being called for every finished node which should be added
      # to the content release.
      #  (must implement ContentReleaseWriterInterface)
      contentReleaseWriters:
        gzipCompressed:
          className: Flowpack\DecoupledContentStore\NodeRendering\Extensibility\ContentReleaseWriters\GzipWriter
        legacy:
          className: Flowpack\DecoupledContentStore\NodeRendering\Extensibility\ContentReleaseWriters\LegacyWriter

    redisKeyPostfixesForEachRelease:
      # each content release starts with a fixed prefix "contentRelease:[releaseId]:", and afterwards
      # follows a part which needs to be registered here. This is needed for synchronization between different
      # content stores and cleanup of old releases.
      # the transfer setting can either be a boolean value for all redis content stores or an object that specifies
      # *per content store*, if the key should be transferred or not. example for the latter:
      #        transfer:
      #          target_live: false
      #          '*': true
      data:
        redisKeyPostfix: 'data'
        transfer: true
        transferMode: 'hash_incremental'
        isRequired: true
      enumerationDocumentNodes:
        redisKeyPostfix: 'enumeration:documentNodes'
        transfer: true
        transferMode: 'dump'
        isRequired: true
      inProgressRenderings:
        redisKeyPostfix: 'inProgressRenderings'
        transfer: false
        transferMode: 'dump'
        isRequired: false
      metainfo:
        redisKeyPostfix: 'meta:info'
        transfer: true
        transferMode: 'dump'
        isRequired: true
      metaUrls:
        redisKeyPostfix: 'meta:urls'
        transfer: true
        transferMode: 'dump'
        isRequired: true
      renderedDocuments:
        redisKeyPostfix: 'renderedDocuments'
        transfer: true
        transferMode: 'hash_incremental'
        isRequired: true
      renderingErrors:
        redisKeyPostfix: 'renderingErrors'
        transfer: true
        transferMode: 'dump'
        isRequired: false
      renderingJobQueue:
        redisKeyPostfix: 'renderingJobQueue'
        transfer: false
        transferMode: 'dump'
        isRequired: false
      renderedMetadata:
        redisKeyPostfix: 'renderedMetadata'
        transfer: true
        transferMode: 'hash_incremental'
        isRequired: true
      renderingStatistics:
        redisKeyPostfix: 'renderingStatistics'
        transfer: true
        transferMode: 'dump'
        isRequired: true

    # can be used on the consuming site to ensure non-breaking deployments for changes in the config
    configEpoch:
      current: '1'
      previous: ~


    resourceSync:
      targets: {  }
      #
      # Target configuration for resource publication / sync
      #
      #  -
      #    host: localhost
      #    port: ''
      #    user: ''
      #    directory: '../nginx/frontend/resources/'
Neos:
  Neos:
    fusion:
      autoInclude:
        Flowpack.DecoupledContentStore: true
    modules:
      'administration':
        submodules:
          'contentstore':
            label: 'Content Store'
            controller: 'Flowpack\DecoupledContentStore\Controller\BackendController'
            description: 'Decoupled Content Publishing'
            icon: 'fas fa-exchange'
            mainStylesheet: 'Lite'

  Flow:
    resource:
      targets:
        localWebDirectoryStaticResourcesTarget:
          target: Flowpack\DecoupledContentStore\Transfer\Resource\Target\MultisiteFileSystemSymlinkTarget
        localWebDirectoryPersistentResourcesTarget:
          target: Flowpack\DecoupledContentStore\Transfer\Resource\Target\MultisiteFileSystemSymlinkTarget

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Flowpack.DecoupledContentStore:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Flowpack\DecoupledContentStore\Controller\.*'
    mvc:
      routes:
        'Flowpack.DecoupledContentStore':
          position: 'before Neos.Neos'
